server:
  # 端口
  port: 6001
  servlet:
    # 项目名称
    context-path: /practise-ms-springboot
spring:
  datasource:
    margin:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/tyfo_localhost?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
      username: root
      password: root